version: "3"
services:
  redis-server:
    image: 'redis:alpine'
    restart: "always"
  rabbitmq-server:
    image: 'rabbitmq:alpine'
    restart: "always"
  web:
    build: .
    ports:
      - "4000:4000"
    
